//! Embeds the application icon into the Windows executable, so Explorer, the Start menu and
//! installer shortcuts show the same icon as the window and the tray.

const ICON: &str = "assets/nvidia-mem-replay.ico";

fn main() {
    println!("cargo:rerun-if-changed={ICON}");
    #[cfg(windows)]
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        // The icon is generated by the application itself (`nvidia-mem-replay icon <path>`),
        // so a checkout without it still builds, just without the embedded resource.
        if !std::path::Path::new(ICON).is_file() {
            println!("cargo:warning={ICON} is missing; the executable gets no icon resource");
            return;
        }
        winresource::WindowsResource::new()
            .set_icon(ICON)
            .set("ProductName", "nvidia-mem-replay")
            .set(
                "FileDescription",
                "NVIDIA Instant Replay temporary storage in RAM",
            )
            .compile()
            .expect("embed the Windows icon resource");
    }
}
